### ISSUE TITLE
Mac 10.14 Mojave error

### ISSUE THREAD

**Issue by bvkimball** [node-3d/glfw-raub#21]
```
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_respondsToSelector
  Referenced from: ./node_modules/glfw-raub/bin-osx/../../deps-opengl-raub/bin-osx/glfw.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_respondsToSelector
  Referenced from: ./node_modules/glfw-raub/bin-osx/../../deps-opengl-raub/bin-osx/glfw.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
```

found a similar error here: https://github.com/koekeishiya/yabai/issues/371, seem like maybe you could add argument `-mmacosx-version-min=10.13` to support older macs maybe.  Updating my Mac to see if my error goes away :)

**Comment by raub** [comment]
Hello! It was compiled with 10.15... And in future I am likely to start using mac 11 (in GitHub Actions). I wonder if `-mmacosx-version-min=10.13` is going to work that far, and properly.

**Comment by bvkimball** [comment]
Yeah, i updated my mac and it working now. Really just stumbling through getting everything setup, ran into the error and thought i would post it just incase someone else gets stuck.

**Comment by blancalarraga** [comment]
Could you give the details on what you did? I am not an expert with computers but I am having the same error with Mojave and I do not know in which file should I include the argument you mentioned.
Thanks!!

**Comment by raub** [comment]
@blancalarraga the error seems to have been resolved by updating the MAC to a more recent OS version
