### ISSUE TITLE
Vulkan API support?

### ISSUE THREAD

**Issue by ghost** [node-3d/glfw-raub#23]
I would like support for things from the Vulkan API. I'm just developing my bindings for that. And I need support for Vulkan API Surface from GLFW.

**Comment by raub** [comment]
Which specific methods and interactions does this imply? I've found this page related to the topic https://www.glfw.org/docs/latest/vulkan_guide.html, so it looks like simply adding those functions to JS exports would allow to move forward with the issue.

**Comment by raub** [comment]
@unit-a-user can you try https://github.com/node-3d/glfw-raub/releases/tag/4.8.0 this release to see if the Vulkan API works for you?
