### ISSUE TITLE
Missing 2nd parameter (value) in call to setInputMode window.js

### ISSUE THREAD

**Issue by chadams77** [node-3d/glfw-raub#6]
The wrapper function in window.js only passes the mode parameter, needs to pass the value parameter as well

**Comment by raub** [comment]
Hello! Could you please clarify which specific wrapper function you've mentioned? Would be perfect to have a link to that exact line.

Also it is important whether you use the latest **master** branch from Github or the package from NPM, because they have diverged a bit lately.

**Comment by chadams77** [comment]
@raub https://github.com/node-3d/glfw-raub/blob/master/js/window.js#L345 I'm using the NPM package, but going by that line the issue is still in master

**Comment by raub** [comment]
Thanks, I'll fix that. For now you may use `glfw.setInputMode(window._window, mode, value);` as a workaround.

The fix will be available on NPM only after I complete the N-API related modifications of the core packages.

**Comment by raub** [comment]
New NAPI build is now available on NPM as `glfw-raub@4.0.0`, the ultimate fix for this issue is a part of the release.
