### ISSUE TITLE
On retina display all examples is smaller by half

### ISSUE THREAD

**Issue by justgook** [node-3d/glfw-raub#7]
When you ran example on Retina display (devicePixelRatio = 2)

![image](https://user-images.githubusercontent.com/306976/71693768-f589ca00-2db5-11ea-9185-4a2f693d1f7b.png)

**Comment by raub** [comment]
Hello. I see a possible fix for this. But I don't have any means to test it on a real Retina. So I'll write back as soon as it will be ready for test.

**Comment by justgook** [comment]
looks like that is just webGL example problem - that just must be added `devicePixelRatio`

BTW - great project have no clue why i not faced it before

**Comment by raub** [comment]
https://github.com/node-3d/glfw-raub/releases/tag/4.2.0-rc Please try an OSX binary from this pre-release, just unpack and replace it in your node_modules dir.

**Comment by justgook** [comment]
https://github.com/node-3d/webgl-raub/blob/master/examples/lesson05.js

When Start APP:
![image](https://user-images.githubusercontent.com/306976/71723388-265d1400-2e35-11ea-88c0-39015ca14aae.png)

When Resize Window:
![image](https://user-images.githubusercontent.com/306976/71723395-2bba5e80-2e35-11ea-8024-928a3bc4c05c.png)

**Comment by raub** [comment]
https://github.com/node-3d/glfw-raub/blob/master/js/window.js#L221
Now some JS has to be touched, `this.emit('resize', this.framebufferSize);` will probably do the trick for the correct initial size. If so, I'll pack a new release with these fixes.

**Comment by justgook** [comment]
looks like that is not really correct place for change:
`this.emit('resize', this.framebufferSize);` - have no effect
`setTimeout(()=>this.emit('resize', this.framebufferSize), 0);` - works (but that is really bad way)

**Comment by raub** [comment]
Oh I see now, the example also tries to get width/height from "canvas" (line 59), so the changes should get a bit more thorough. But we're on the right track... I'll notify you when there is something to try.

BTW, did you try [3d-core-raub](https://github.com/node-3d/3d-core-raub) (it doesn't fix the issue, but still)? It has THREEJS bundled and some more stuff.

**Comment by justgook** [comment]
im planing it to use for something different: there is language [Elm](https://elm-lang.org/), it have it own implementation of [webGL](https://package.elm-lang.org/packages/elm-explorations/webgl/latest/) 
after that there is nice [playground "framework" ](https://package.elm-lang.org/packages/evancz/elm-playground/latest/) - that i [forked](https://github.com/justgook/webgl-playground) - and created WebGL version of that..

My target is using that fork create application, that can run in glfw-openGL, from Node, that i then pack into singe executable by use of [pkg](https://www.npmjs.com/package/pkg)

btw - all steps looks like work - need to do some clean up - and that issue was just on track while i was investigating.

any way i need custom mock of Document and Window - so that "ready to use solution" isn't for me

BTW - here is [Example Game](https://game2.z0.lv/) that i would like wrap into "native"

**Comment by raub** [comment]
Can you try the tag [v4.2.0-rc2](https://github.com/node-3d/glfw-raub/releases/tag/v4.2.0-rc2) for a possible fix?

I updated both binaries and js to use mostly logical sizes. Now I wonder what does cursor position report, because GLFW doc says it is in "screen coordinates" anyway.

**Comment by raub** [comment]
Fixed in glfw-raub@4.2.0
