### ISSUE TITLE
Event KeyUp and KeyDown missing some values

### ISSUE THREAD

**Issue by justgook** [node-3d/glfw-raub#8]
prop `key` of event missing values: `ArrowUp`,`ArrowRight` ,`ArrowDown` ,`ArrowLeft` ,`Alt` ,`Meta` ,`Control` ,`Shift` ,`CapsLock` ,`Tab` ,`Escape`

https://github.com/node-3d/glfw-raub/blob/master/js/window.js#L472-L474

**Comment by justgook** [comment]
BTW: `code: 'Keya',` also is wrong - it should be `KeyA`

**Comment by raub** [comment]
Fixed in glfw-raub@4.2.0
